template = ""
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
