template = ""
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
