template = ""
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
